<?php
/**
 * @file
 * Code for the CampusWiki Profile feature.
 */

include_once 'campuswiki_profile.features.inc';
module_load_include('inc', 'campuswiki_profile', 'campuswiki_profile.block');
module_load_include('inc', 'campuswiki_basic', 'campuswiki_basic.functions');
module_load_include('inc', 'campuswiki_profile', 'campuswiki_profile');

/**
 * Implements hook_block_info().
 *
 */
function campuswiki_profile_block_info() {
  $blocks['cw_user_info'] = array(
    'info' => t('Campuswiki User Info'),
    'cache' => DRUPAL_NO_CACHE
    // DRUPAL_CACHE_PER_ROLE will be assumed if not set.
  );
  
  // create block to list user groups
  $blocks['cw_user_groups'] = array(
    'info' => t('Campuswiki User Groups'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  // create user connections block
  $blocks['cw_user_connections'] = array(
    'info' => t('Campuswiki User Connections'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  // create user message block
  $blocks['cw_user_message'] = array(
    'info' => t('CampusWiki User Message'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 *
 */
function campuswiki_profile_block_view($delta = '') {

  $block = array(); 

  switch ($delta) {
    
    case 'cw_user_info':
      $content = campuswiki_profile_user_info_block();
      if (!empty($content)) {
        $block['subject'] = t('User Information');
        $block['content'] = $content;
      }
      break;
    
    case 'cw_user_groups':
      $count = campuswiki_profile_user_groups_count();
      if ($count > 0) {
        $content = campuswiki_profile_user_groups_block();
        if (!empty($content)) {
          $block['subject'] = t('Groups (@count)', array('@count' => $count));
          $block['content'] = $content;
        }
      }
      break;
    
    case 'cw_user_connections':
      $content = campuswiki_profile_user_connection_block();
      if (!empty($content)) {
        $block['subject'] = t('Connections');
        $block['content'] = $content;
      }
      break;
    
    case 'cw_user_message':
      $block['subject'] = t('User Message');
      $block['content'] = campuswiki_basic_user_message_block(); 
  }
  return $block;
}