<?php
/**
 * @file
 * Code for the CampusWiki Events feature.
 */

include_once 'campuswiki_events.features.inc';
module_load_include('inc', 'campuswiki_events', 'campuswiki_events');
module_load_include('inc', 'campuswiki_events', 'campuswiki_events.block');
module_load_include('inc', 'campuswiki_events', 'campuswiki_events.theme');

/**
 * Implements hook_theme().
 */
function campuswiki_events_theme() {
  return array(
    'campuswiki_events_flipcard' => array(
      'variables' => array('nid' => NULL),
    ),
    'campuswiki_events_rsvp_badge' => array(
      'variables' => array('nid' => NULL, 'link' => NULL),
    ),
    'campuswiki_events_rsvp_button' => array(
      'variables' => array('nid' => NULL, 'link' => NULL),
    ),
  );
}


/**
 * Implements hook_block_info().
 *
 */
function campuswiki_events_block_info() {
  $blocks['frontpage_event'] = array(
    'info' => t('Frontpage event'),
    'cache' => DRUPAL_NO_CACHE
    // DRUPAL_CACHE_PER_ROLE will be assumed if not set.
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 */
function campuswiki_events_block_view($delta = '') {

  $block = array(); 

  switch ($delta) {
    
    case 'frontpage_event':
      $content = campuswiki_events_frontpage_block();
      if (!empty($content)) {
        $block['subject'] = $content['title'];
        $block['content'] = $content['body'];
      }
      break;

  }
  return $block;
}
