<?php
/**
 * @file
 * Code for the CampusWiki Basic feature.
 */

include_once('campuswiki_basic.features.inc');
module_load_include('inc', 'campuswiki_basic', 'campuswiki_basic.theme');

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 */
function campuswiki_basic_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels' && $plugin_type == 'layouts') {
    return "plugins/$plugin_type";
  }
}

//function campuswiki_basic_features_menu() {
//  $menu_options = menu_get_menus();
//  //$menu_options = menu_navigation_links('menu-features');
//  return $menu_options;
//}
//
//$menus_options = campuswiki_basic_features_menu();
//dpm($menus_options);


/**
 * Implements hook_block_info
 */
function campuswiki_basic_block_info() {
  $blocks['cw_main_menu'] = array(
    'info' => t('CW Main Menu'),
    'cache' => DRUPAL_NO_CACHE
    // DRUPAL_CACHE_PER_ROLE will be assumed if not set.
  );
  
  return $blocks;
}


/**
 * Implements hook_block_view().
 *
 */
function campuswiki_basic_block_view($delta = '') { 

  $block = array(); 

  switch ($delta) {
    
    case 'cw_main_menu':
      $features_menu = menu_navigation_links('main-menu');
      //campuswiki_basic_icon_links($features_menu); 
      $block['subject'] = t('');
      $block['content'] = array(
        '#prefix' => '<div id="navigation">',
        '#suffix' => '</div>',
        '#theme' => 'links',
        //'#links' => campuswiki_basic_icon_links($features_menu),
        '#links' => $features_menu,
        '#attributes' => array(
          'class' => array('links', 'inline', 'clearfix'),
          'id' => 'features-menu',
        ),
      );
      break;

  }
  return $block;
}