<?php
/**
 * @file
 * Code for the CampusWiki Basic feature.
 */

include_once('campuswiki_basic.features.inc');
module_load_include('inc', 'campuswiki_basic', 'campuswiki_basic.theme');

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 */
function campuswiki_basic_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels' && $plugin_type == 'layouts') {
    return "plugins/$plugin_type";
  }
}

//function campuswiki_basic_features_menu() {
//  $menu_options = menu_get_menus();
//  //$menu_options = menu_navigation_links('menu-features');
//  return $menu_options;
//}
//
//$menus_options = campuswiki_basic_features_menu();
//dpm($menus_options);


/**
 * Implements hook_block_info
 */
function campuswiki_basic_block_info() {
  $blocks['cw_main_menu'] = array(
    'info' => t('CW Main Menu'),
    'cache' => DRUPAL_NO_CACHE,
    // DRUPAL_CACHE_PER_ROLE will be assumed if not set.
  );
  
  $blocks['cw_copyright'] = array(
    'info' => t('CW Copyright'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}


/**
 * Implements hook_block_view().
 *
 */
function campuswiki_basic_block_view($delta = '') { 

  $block = array(); 

  switch ($delta) {
    
    case 'cw_main_menu':
      $features_menu = menu_navigation_links('main-menu');
      //campuswiki_basic_icon_links($features_menu); 
      $block['subject'] = t('Main Menu');
      $block['content'] = array(
        '#prefix' => '<nav id="nav-main-menu">',
        '#suffix' => '</nav>',
        '#theme' => 'links',
        //'#links' => campuswiki_basic_icon_links($features_menu),
        '#links' => $features_menu,
        '#attributes' => array(
          'class' => array('main-menu', 'links', 'inline', 'clearfix'),
          'id' => 'main-menu',
        ),
      );
      break;
    
    case 'cw_copyright':
      $startyear = 2013;
      $currentyear = date('Y');
      $year = ($currentyear > $startyear) ? $startyear . ' - ' . $currentyear : $startyear;
      $block['suject'] = t('Copyright');
      $block['content'] = '<div class="copyright">&#169; Copyright '
        . $year
        . ' <a href="http://www.conzultrix.com">Conzultrix</a>. '
        . 'All Rights Reserved'
        . '</div>';

  }
  return $block;
}